# Generated by Django 3.2.19 on 2026-02-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_booking_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.IntegerField(default=200),
        ),
    ]
